/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
4million = 4_000_000
 */

#include<iostream>
#define MILLION 1000000

using namespace std;

int main()
{
  long int a,b,c,sum;
  a = b = c = 1;
  sum = 0;
  while( c < 4*MILLION )
  {
    c = a + b;
    if( c % 2 == 0)
      sum += c;
	a = b;
	b = c;
  }
  cout<<sum;
}
